name: Build & deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: homestead
          MYSQL_PASSWORD: secret
          MYSQL_DATABASE: homestead
          MYSQL_ROOT_PASSWORD: secret
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      
      - name: Configure PHP 8.0
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.1
          extensions: mbstring, ctype, fileinfo, openssl, PDO, pdo_mysql, bcmath, json, tokenizer, xml 
      
      - name: Composer install
        run: |
          composer install --no-dev --no-interaction --prefer-dist  
          chmod -R 777 storage bootstrap/cache      

      - name: Compile CSS and Javascript
        run: |
          npm install
          npm run build
          
      - name: Run migrations 
        run: |
          php -r "file_exists('.env') || copy('.env.workflow', '.env');"
          php artisan migrate --no-interaction
          php artisan key:generate

      - name: Run Testsuite
        run: ./vendor/bin/phpunit tests/          